import { Country } from '@/types'; // Ensure this path is correct

export const mockCountries: Country[] = [
  // Existing Countries (with minor updates for consistency)
  {
    id: 'fr',
    name: 'France',
    code: 'FR',
    flagUrl: 'https://flagcdn.com/w320/fr.png', // Using w320 for better resolution
    headerImageUrl: 'https://images.pexels.com/photos/161901/paris-sunset-france-monument-161901.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['French'],
    capital: 'Paris',
    region: 'Europe',
    currency: 'Euro (EUR)',
    timeZone: 'UTC+1 (CET), UTC+2 (CEST)',
    isBookmarked: false, // Added for consistency
  },
  {
    id: 'jp',
    name: 'Japan',
    code: 'JP',
    flagUrl: 'https://flagcdn.com/w320/jp.png',
    headerImageUrl: 'https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Japanese'],
    capital: 'Tokyo',
    region: 'Asia',
    currency: 'Japanese Yen (JPY)',
    timeZone: 'UTC+9 (JST)',
    isBookmarked: false,
  },
  {
    id: 'br',
    name: 'Brazil',
    code: 'BR',
    flagUrl: 'https://flagcdn.com/w320/br.png',
    headerImageUrl: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Portuguese'],
    capital: 'Brasília',
    region: 'South America',
    currency: 'Brazilian Real (BRL)',
    timeZone: 'UTC-2 to UTC-5',
    isBookmarked: false,
  },
  {
    id: 'za',
    name: 'South Africa',
    code: 'ZA',
    flagUrl: 'https://flagcdn.com/w320/za.png',
    headerImageUrl: 'https://images.pexels.com/photos/2350336/pexels-photo-2350336.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Zulu', 'Xhosa', 'Afrikaans', 'English', 'Sotho', 'Tswana', 'Venda', 'Tsonga', 'Swati', 'Ndebele', 'Pedi'],
    capital: 'Pretoria (executive), Bloemfontein (judicial), Cape Town (legislative)',
    region: 'Africa',
    currency: 'South African Rand (ZAR)',
    timeZone: 'UTC+2 (SAST)',
    isBookmarked: false,
  },
  {
    id: 'ca',
    name: 'Canada',
    code: 'CA',
    flagUrl: 'https://flagcdn.com/w320/ca.png',
    headerImageUrl: 'https://images.pexels.com/photos/417054/pexels-photo-417054.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['English', 'French'],
    capital: 'Ottawa',
    region: 'North America',
    currency: 'Canadian Dollar (CAD)',
    timeZone: 'UTC-3.5 to UTC-8',
    isBookmarked: false,
  },
  {
    id: 'in',
    name: 'India',
    code: 'IN',
    flagUrl: 'https://flagcdn.com/w320/in.png',
    headerImageUrl: 'https://images.pexels.com/photos/3573351/pexels-photo-3573351.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Hindi', 'English'], // And many other official languages
    capital: 'New Delhi',
    region: 'Asia',
    currency: 'Indian Rupee (INR)',
    timeZone: 'UTC+5:30 (IST)',
    isBookmarked: false,
  },
  {
    id: 'eg',
    name: 'Egypt',
    code: 'EG',
    flagUrl: 'https://flagcdn.com/w320/eg.png',
    headerImageUrl: 'https://images.pexels.com/photos/161251/egypt-pyramid-giza-161251.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Arabic'],
    capital: 'Cairo',
    region: 'Africa',
    currency: 'Egyptian Pound (EGP)',
    timeZone: 'UTC+2 (EET)',
    isBookmarked: false,
  },
  {
    id: 'au',
    name: 'Australia',
    code: 'AU',
    flagUrl: 'https://flagcdn.com/w320/au.png',
    headerImageUrl: 'https://images.pexels.com/photos/1878293/pexels-photo-1878293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['English'],
    capital: 'Canberra',
    region: 'Oceania',
    currency: 'Australian Dollar (AUD)',
    timeZone: 'UTC+8 to UTC+10.5',
    isBookmarked: false,
  },

  // New Additions
  {
    id: 'de',
    name: 'Germany',
    code: 'DE',
    flagUrl: 'https://flagcdn.com/w320/de.png',
    headerImageUrl: 'https://images.pexels.com/photos/1300972/pexels-photo-1300972.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['German'],
    capital: 'Berlin',
    region: 'Europe',
    currency: 'Euro (EUR)',
    timeZone: 'UTC+1 (CET), UTC+2 (CEST)',
    isBookmarked: false,
  },
  {
    id: 'it',
    name: 'Italy',
    code: 'IT',
    flagUrl: 'https://flagcdn.com/w320/it.png',
    headerImageUrl: 'https://images.pexels.com/photos/1797161/pexels-photo-1797161.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Italian'],
    capital: 'Rome',
    region: 'Europe',
    currency: 'Euro (EUR)',
    timeZone: 'UTC+1 (CET), UTC+2 (CEST)',
    isBookmarked: false,
  },
  {
    id: 'es',
    name: 'Spain',
    code: 'ES',
    flagUrl: 'https://flagcdn.com/w320/es.png',
    headerImageUrl: 'https://images.pexels.com/photos/3889929/pexels-photo-3889929.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Spanish'], // Castilian, Catalan, Galician, Basque
    capital: 'Madrid',
    region: 'Europe',
    currency: 'Euro (EUR)',
    timeZone: 'UTC+1 (CET), UTC+2 (CEST)',
    isBookmarked: false,
  },
  {
    id: 'gb', // Note: Using GB for United Kingdom as per ISO 3166-1 alpha-2 often used in APIs
    name: 'United Kingdom',
    code: 'GB',
    flagUrl: 'https://flagcdn.com/w320/gb.png',
    headerImageUrl: 'https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['English'],
    capital: 'London',
    region: 'Europe',
    currency: 'Pound Sterling (GBP)',
    timeZone: 'UTC+0 (GMT), UTC+1 (BST)',
    isBookmarked: false,
  },
  {
    id: 'us',
    name: 'United States',
    code: 'US',
    flagUrl: 'https://flagcdn.com/w320/us.png',
    headerImageUrl: 'https://images.pexels.com/photos/96381/new-york-city-nyc-buildings-skyline-96381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['English'], // Spanish is also widely spoken
    capital: 'Washington, D.C.',
    region: 'North America',
    currency: 'United States Dollar (USD)',
    timeZone: 'UTC-4 to UTC-10',
    isBookmarked: false,
  },
  {
    id: 'cn',
    name: 'China',
    code: 'CN',
    flagUrl: 'https://flagcdn.com/w320/cn.png',
    headerImageUrl: 'https://images.pexels.com/photos/247851/pexels-photo-247851.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Mandarin Chinese'],
    capital: 'Beijing',
    region: 'Asia',
    currency: 'Renminbi (CNY)',
    timeZone: 'UTC+8 (CST)',
    isBookmarked: false,
  },
  {
    id: 'ru',
    name: 'Russia',
    code: 'RU',
    flagUrl: 'https://flagcdn.com/w320/ru.png',
    headerImageUrl: 'https://images.pexels.com/photos/3695645/pexels-photo-3695645.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Russian'],
    capital: 'Moscow',
    region: 'Europe/Asia',
    currency: 'Russian Ruble (RUB)',
    timeZone: 'UTC+2 to UTC+12',
    isBookmarked: false,
  },
  {
    id: 'mx',
    name: 'Mexico',
    code: 'MX',
    flagUrl: 'https://flagcdn.com/w320/mx.png',
    headerImageUrl: 'https://images.pexels.com/photos/163452/chichen-itza-mexico-yucatan-163452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Spanish'],
    capital: 'Mexico City',
    region: 'North America',
    currency: 'Mexican Peso (MXN)',
    timeZone: 'UTC-5 to UTC-8',
    isBookmarked: false,
  },
  {
    id: 'ar',
    name: 'Argentina',
    code: 'AR',
    flagUrl: 'https://flagcdn.com/w320/ar.png',
    headerImageUrl: 'https://images.pexels.com/photos/1102777/pexels-photo-1102777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Spanish'],
    capital: 'Buenos Aires',
    region: 'South America',
    currency: 'Argentine Peso (ARS)',
    timeZone: 'UTC-3',
    isBookmarked: false,
  },
  {
    id: 'kr',
    name: 'South Korea',
    code: 'KR',
    flagUrl: 'https://flagcdn.com/w320/kr.png',
    headerImageUrl: 'https://images.pexels.com/photos/1909678/pexels-photo-1909678.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Korean'],
    capital: 'Seoul',
    region: 'Asia',
    currency: 'South Korean Won (KRW)',
    timeZone: 'UTC+9 (KST)',
    isBookmarked: false,
  },
  {
    id: 'tr',
    name: 'Turkey',
    code: 'TR',
    flagUrl: 'https://flagcdn.com/w320/tr.png',
    headerImageUrl: 'https://images.pexels.com/photos/772690/pexels-photo-772690.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Turkish'],
    capital: 'Ankara',
    region: 'Asia/Europe',
    currency: 'Turkish Lira (TRY)',
    timeZone: 'UTC+3',
    isBookMAD: false, // Typo, assuming isBookmarked
    isBookmarked: false,
  },
  {
    id: 'sa',
    name: 'Saudi Arabia',
    code: 'SA',
    flagUrl: 'https://flagcdn.com/w320/sa.png',
    headerImageUrl: 'https://images.pexels.com/photos/3690790/pexels-photo-3690790.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Arabic'],
    capital: 'Riyadh',
    region: 'Asia',
    currency: 'Saudi Riyal (SAR)',
    timeZone: 'UTC+3',
    isBookmarked: false,
  },
  {
    id: 'id',
    name: 'Indonesia',
    code: 'ID',
    flagUrl: 'https://flagcdn.com/w320/id.png',
    headerImageUrl: 'https://images.pexels.com/photos/2166559/pexels-photo-2166559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Indonesian'],
    capital: 'Jakarta',
    region: 'Asia',
    currency: 'Indonesian Rupiah (IDR)',
    timeZone: 'UTC+7 to UTC+9',
    isBookmarked: false,
  },
  {
    id: 'nl',
    name: 'Netherlands',
    code: 'NL',
    flagUrl: 'https://flagcdn.com/w320/nl.png',
    headerImageUrl: 'https://images.pexels.com/photos/58673/pexels-photo-58673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Dutch'],
    capital: 'Amsterdam',
    region: 'Europe',
    currency: 'Euro (EUR)',
    timeZone: 'UTC+1 (CET), UTC+2 (CEST)',
    isBookmarked: false,
  },
  {
    id: 'ch',
    name: 'Switzerland',
    code: 'CH',
    flagUrl: 'https://flagcdn.com/w320/ch.png',
    headerImageUrl: 'https://images.pexels.com/photos/772429/pexels-photo-772429.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['German', 'French', 'Italian', 'Romansh'],
    capital: 'Bern',
    region: 'Europe',
    currency: 'Swiss Franc (CHF)',
    timeZone: 'UTC+1 (CET), UTC+2 (CEST)',
    isBookmarked: false,
  },
  {
    id: 'se',
    name: 'Sweden',
    code: 'SE',
    flagUrl: 'https://flagcdn.com/w320/se.png',
    headerImageUrl: 'https://images.pexels.com/photos/162971/architecture-building-historical-place-sightseeing-162971.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Swedish'],
    capital: 'Stockholm',
    region: 'Europe',
    currency: 'Swedish Krona (SEK)',
    timeZone: 'UTC+1 (CET), UTC+2 (CEST)',
    isBookmarked: false,
  },
  {
    id: 'th',
    name: 'Thailand',
    code: 'TH',
    flagUrl: 'https://flagcdn.com/w320/th.png',
    headerImageUrl: 'https://images.pexels.com/photos/373904/pexels-photo-373904.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    languages: ['Thai'],
    capital: 'Bangkok',
    region: 'Asia',
    currency: 'Thai Baht (THB)',
    timeZone: 'UTC+7',
    isBookmarked: false,
  },
  // ... (Continue adding more countries to reach ~50)
];